name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create version tag
        run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build --file Dockerfile --tag ns2.35_nam1.15:${{ env.VERSION }} .
          echo "Build completed successfully"

      - name: Save Docker image as tar to be saved as artifact artifact
        run: docker save ns2.35_nam1.15:${{ env.VERSION }} -o ns2-image-${{ env.VERSION }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ns2-image-${{ env.VERSION }}
          path: ns2-image-${{ env.VERSION }}.tar
          retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create version tag
      run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ns2-image-${{ env.VERSION }}
    - name: Load Docker image
      run: docker load -i ns2-image-${{ env.VERSION }}.tar

    - name: scan using Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy image ns2.35_nam1.15:${{ env.VERSION }}

    - name: open high severity vulnerabilities as issues
      uses: aquasecurity/trivy-action@main
      with:
        image-ref: ns2.35_nam1.15:${{ env.VERSION }}
        severity: HIGH,CRITICAL
        format: 'table'
        exit-code: '0'
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
  publish:

    runs-on: ubuntu-latest
    needs: security-scan
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Create version tag
      run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

    - name: Push the Docker image
      run: docker push ns2.35_nam1.15:${{ env.VERSION }}
